// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { ChartDB } from '../chart-db'
import { ChartService } from '../chart.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-chartstable',
  templateUrl: './charts-table.component.html',
  styleUrls: ['./charts-table.component.css'],
})
export class ChartsTableComponent implements OnInit {

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Chart instances
  selection: SelectionModel<ChartDB> = new (SelectionModel)
  initialSelection = new Array<ChartDB>()

  // the data source for the table
  charts: ChartDB[] = []
  matTableDataSource: MatTableDataSource<ChartDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.charts
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (chartDB: ChartDB, property: string) => {
      switch (property) {
        case 'ID':
          return chartDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return chartDB.Name;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (chartDB: ChartDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the chartDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += chartDB.Name.toLowerCase()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private chartService: ChartService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of chart instances
    public dialogRef: MatDialogRef<ChartsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.chartService.ChartServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getCharts()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
      ]
      this.selection = new SelectionModel<ChartDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getCharts()
    this.matTableDataSource = new MatTableDataSource(this.charts)
  }

  getCharts(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.charts = this.frontRepo.Charts_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries
        
        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let chart of this.charts) {
            let ID = this.dialogData.ID
            let revPointer = chart[this.dialogData.ReversePointer as keyof ChartDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(chart)
            }
            this.selection = new SelectionModel<ChartDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ChartDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ChartDB[]
          for (let associationInstance of sourceField) {
            let chart = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ChartDB
            this.initialSelection.push(chart)
          }

          this.selection = new SelectionModel<ChartDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.charts
      }
    )
  }

  // newChart initiate a new chart
  // create a new Chart objet
  newChart() {
  }

  deleteChart(chartID: number, chart: ChartDB) {
    // list of charts is truncated of chart before the delete
    this.charts = this.charts.filter(h => h !== chart);

    this.chartService.deleteChart(chartID).subscribe(
      chart => {
        this.chartService.ChartServiceChanged.next("delete")
      }
    );
  }

  editChart(chartID: number, chart: ChartDB) {

  }

  // display chart in router
  displayChartInRouter(chartID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongngxcharts_go-" + "chart-display", chartID])
  }

  // set editor outlet
  setEditorRouterOutlet(chartID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongngxcharts_go_editor: ["github_com_fullstack_lang_gongngxcharts_go-" + "chart-detail", chartID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(chartID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongngxcharts_go_presentation: ["github_com_fullstack_lang_gongngxcharts_go-" + "chart-presentation", chartID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.charts.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.charts.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ChartDB>()

      // reset all initial selection of chart that belong to chart
      for (let chart of this.initialSelection) {
        let index = chart[this.dialogData.ReversePointer as keyof ChartDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(chart)

      }

      // from selection, set chart that belong to chart
      for (let chart of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = chart[this.dialogData.ReversePointer as keyof ChartDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(chart)
      }


      // update all chart (only update selection & initial selection)
      for (let chart of toUpdate) {
        this.chartService.updateChart(chart)
          .subscribe(chart => {
            this.chartService.ChartServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ChartDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedChart = new Set<number>()
      for (let chart of this.initialSelection) {
        if (this.selection.selected.includes(chart)) {
          // console.log("chart " + chart.Name + " is still selected")
        } else {
          console.log("chart " + chart.Name + " has been unselected")
          unselectedChart.add(chart.ID)
          console.log("is unselected " + unselectedChart.has(chart.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let chart = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ChartDB
      if (unselectedChart.has(chart.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ChartDB>) = new Array<ChartDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          chart => {
            if (!this.initialSelection.includes(chart)) {
              // console.log("chart " + chart.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + chart.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = chart.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = chart.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("chart " + chart.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ChartDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
