// generated by ModelGongFileTemplate
package models

import (
	"fmt"
	"log"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"
)

// swagger:ignore
type __void struct{}

// needed for creating set of instances in the stage
var __member __void

// GongStructInterface is the interface met by GongStructs
// It allows runtime reflexion of instances (without the hassle of the "reflect" package)
type GongStructInterface interface {
	GetName() (res string)
	GetFields() (res []string)
	GetFieldStringValue(fieldName string) (res string)
}

// StageStruct enables storage of staged instances
// swagger:ignore
type StageStruct struct { // insertion point for definition of arrays registering instances
	Charts           map[*Chart]struct{}
	Charts_mapString map[string]*Chart

	AllModelsStructCreateCallback AllModelsStructCreateInterface

	AllModelsStructDeleteCallback AllModelsStructDeleteInterface

	BackRepo BackRepoInterface

	// if set will be called before each commit to the back repo
	OnInitCommitCallback          OnInitCommitInterface
	OnInitCommitFromFrontCallback OnInitCommitInterface
	OnInitCommitFromBackCallback  OnInitCommitInterface

	// store the number of instance per gongstruct
	Map_GongStructName_InstancesNb map[string]int
}

type OnInitCommitInterface interface {
	BeforeCommit(stage *StageStruct)
}

type BackRepoInterface interface {
	Commit(stage *StageStruct)
	Checkout(stage *StageStruct)
	Backup(stage *StageStruct, dirPath string)
	Restore(stage *StageStruct, dirPath string)
	BackupXL(stage *StageStruct, dirPath string)
	RestoreXL(stage *StageStruct, dirPath string)
	// insertion point for Commit and Checkout signatures
	CommitChart(chart *Chart)
	CheckoutChart(chart *Chart)
	GetLastCommitFromBackNb() uint
	GetLastPushFromFrontNb() uint
}

// swagger:ignore instructs the gong compiler (gongc) to avoid this particular struct
var Stage StageStruct = StageStruct{ // insertion point for array initiatialisation
	Charts:           make(map[*Chart]struct{}),
	Charts_mapString: make(map[string]*Chart),

	// end of insertion point
	Map_GongStructName_InstancesNb: make(map[string]int),
}

func (stage *StageStruct) Commit() {
	if stage.BackRepo != nil {
		stage.BackRepo.Commit(stage)
	}

	// insertion point for computing the map of number of instances per gongstruct
	stage.Map_GongStructName_InstancesNb["Chart"] = len(stage.Charts)

}

func (stage *StageStruct) Checkout() {
	if stage.BackRepo != nil {
		stage.BackRepo.Checkout(stage)
	}
}

// backup generates backup files in the dirPath
func (stage *StageStruct) Backup(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.Backup(stage, dirPath)
	}
}

// Restore resets Stage & BackRepo and restores their content from the restore files in dirPath
func (stage *StageStruct) Restore(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.Restore(stage, dirPath)
	}
}

// backup generates backup files in the dirPath
func (stage *StageStruct) BackupXL(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.BackupXL(stage, dirPath)
	}
}

// Restore resets Stage & BackRepo and restores their content from the restore files in dirPath
func (stage *StageStruct) RestoreXL(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.RestoreXL(stage, dirPath)
	}
}

// insertion point for cumulative sub template with model space calls
func (stage *StageStruct) getChartOrderedStructWithNameField() []*Chart {
	// have alphabetical order generation
	chartOrdered := []*Chart{}
	for chart := range stage.Charts {
		chartOrdered = append(chartOrdered, chart)
	}
	sort.Slice(chartOrdered[:], func(i, j int) bool {
		return chartOrdered[i].Name < chartOrdered[j].Name
	})
	return chartOrdered
}

// Stage puts chart to the model stage
func (chart *Chart) Stage() *Chart {
	Stage.Charts[chart] = __member
	Stage.Charts_mapString[chart.Name] = chart

	return chart
}

// Unstage removes chart off the model stage
func (chart *Chart) Unstage() *Chart {
	delete(Stage.Charts, chart)
	delete(Stage.Charts_mapString, chart.Name)
	return chart
}

// commit chart to the back repo (if it is already staged)
func (chart *Chart) Commit() *Chart {
	if _, ok := Stage.Charts[chart]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitChart(chart)
		}
	}
	return chart
}

// Checkout chart to the back repo (if it is already staged)
func (chart *Chart) Checkout() *Chart {
	if _, ok := Stage.Charts[chart]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutChart(chart)
		}
	}
	return chart
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of chart to the model stage
func (chart *Chart) StageCopy() *Chart {
	_chart := new(Chart)
	*_chart = *chart
	_chart.Stage()
	return _chart
}

// StageAndCommit appends chart to the model stage and commit to the orm repo
func (chart *Chart) StageAndCommit() *Chart {
	chart.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMChart(chart)
	}
	return chart
}

// DeleteStageAndCommit appends chart to the model stage and commit to the orm repo
func (chart *Chart) DeleteStageAndCommit() *Chart {
	chart.Unstage()
	DeleteORMChart(chart)
	return chart
}

// StageCopyAndCommit appends a copy of chart to the model stage and commit to the orm repo
func (chart *Chart) StageCopyAndCommit() *Chart {
	_chart := new(Chart)
	*_chart = *chart
	_chart.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMChart(chart)
	}
	return _chart
}

// CreateORMChart enables dynamic staging of a Chart instance
func CreateORMChart(chart *Chart) {
	chart.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMChart(chart)
	}
}

// DeleteORMChart enables dynamic staging of a Chart instance
func DeleteORMChart(chart *Chart) {
	chart.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMChart(chart)
	}
}

// for satisfaction of GongStruct interface
func (chart *Chart) GetName() (res string) {
	return chart.Name
}

func (chart *Chart) GetFields() (res []string) {
	// list of fields 
	res = []string{"Name",  }
	return
}

func (chart *Chart) GetFieldStringValue(fieldName string) (res string) {
	switch fieldName {
	// string value of fields
	case "Name":
		res = chart.Name
	}
	return
}

// swagger:ignore
type AllModelsStructCreateInterface interface { // insertion point for Callbacks on creation
	CreateORMChart(Chart *Chart)
}

type AllModelsStructDeleteInterface interface { // insertion point for Callbacks on deletion
	DeleteORMChart(Chart *Chart)
}

func (stage *StageStruct) Reset() { // insertion point for array reset
	stage.Charts = make(map[*Chart]struct{})
	stage.Charts_mapString = make(map[string]*Chart)

}

func (stage *StageStruct) Nil() { // insertion point for array nil
	stage.Charts = nil
	stage.Charts_mapString = nil

}

const marshallRes = `package {{PackageName}}

import (
	"time"

	"{{ModelsPackageName}}"
)

func init() {
	var __Dummy_time_variable time.Time
	_ = __Dummy_time_variable
	InjectionGateway["{{databaseName}}"] = {{databaseName}}Injection
}

// {{databaseName}}Injection will stage objects of database "{{databaseName}}"
func {{databaseName}}Injection() {

	// Declaration of instances to stage{{Identifiers}}

	// Setup of values{{ValueInitializers}}

	// Setup of pointers{{PointersInitializers}}
}

`

const IdentifiersDecls = `
	{{Identifier}} := (&models.{{GeneratedStructName}}{Name: "{{GeneratedFieldNameValue}}"}).Stage()`

const StringInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = ` + "`" + `{{GeneratedFieldNameValue}}` + "`"

const StringEnumInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const NumberInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const PointerFieldInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const SliceOfPointersFieldInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = append({{Identifier}}.{{GeneratedFieldName}}, {{GeneratedFieldNameValue}})`

const TimeInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}}, _ = time.Parse("2006-01-02 15:04:05.999999999 -0700 MST", "{{GeneratedFieldNameValue}}")`

// Marshall marshall the stage content into the file as an instanciation into a stage
func (stage *StageStruct) Marshall(file *os.File, modelsPackageName, packageName string) {

	name := file.Name()

	if !strings.HasSuffix(name, ".go") {
		log.Fatalln(name + " is not a go filename")
	}

	log.Println("filename of marshall output  is " + name)

	res := marshallRes
	res = strings.ReplaceAll(res, "{{databaseName}}", strings.ReplaceAll(path.Base(name), ".go", ""))
	res = strings.ReplaceAll(res, "{{PackageName}}", packageName)
	res = strings.ReplaceAll(res, "{{ModelsPackageName}}", modelsPackageName)

	// map of identifiers
	// var StageMapDstructIds map[*Dstruct]string
	identifiersDecl := ""
	initializerStatements := ""
	pointersInitializesStatements := ""

	id := ""
	decl := ""
	setValueField := ""

	// insertion initialization of objects to stage
	map_Chart_Identifiers := make(map[*Chart]string)
	_ = map_Chart_Identifiers

	chartOrdered := []*Chart{}
	for chart := range stage.Charts {
		chartOrdered = append(chartOrdered, chart)
	}
	sort.Slice(chartOrdered[:], func(i, j int) bool {
		return chartOrdered[i].Name < chartOrdered[j].Name
	})
	identifiersDecl += fmt.Sprintf("\n\n	// Declarations of staged instances of Chart")
	for idx, chart := range chartOrdered {

		id = generatesIdentifier("Chart", idx, chart.Name)
		map_Chart_Identifiers[chart] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Chart")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", chart.Name)
		identifiersDecl += decl

		initializerStatements += fmt.Sprintf("\n\n	// Chart %s values setup", chart.Name)
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(chart.Name))
		initializerStatements += setValueField

	}

	// insertion initialization of objects to stage
	for idx, chart := range chartOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Chart", idx, chart.Name)
		map_Chart_Identifiers[chart] = id

		// Initialisation of values
	}

	res = strings.ReplaceAll(res, "{{Identifiers}}", identifiersDecl)
	res = strings.ReplaceAll(res, "{{ValueInitializers}}", initializerStatements)
	res = strings.ReplaceAll(res, "{{PointersInitializers}}", pointersInitializesStatements)

	fmt.Fprintln(file, res)
}

// unique identifier per struct
func generatesIdentifier(gongStructName string, idx int, instanceName string) (identifier string) {

	identifier = instanceName
	// Make a Regex to say we only want letters and numbers
	reg, err := regexp.Compile("[^a-zA-Z0-9]+")
	if err != nil {
		log.Fatal(err)
	}
	processedString := reg.ReplaceAllString(instanceName, "_")

	identifier = fmt.Sprintf("__%s__%06d_%s", gongStructName, idx, processedString)

	return
}

// insertion point of enum utility functions
